import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { TimeEntriesService } from '../modules/time-entries/time-entries.service';
import { IncidentsService } from '../modules/incidents/incidents.service';

async function testAutoExit() {
  console.log('🧪 Testing auto-exit detection...');
  
  const app = await NestFactory.createApplicationContext(AppModule);
  const timeEntriesService = app.get(TimeEntriesService);
  const incidentsService = app.get(IncidentsService);
  
  // User ID del empleado
  const userId = 'b561950b-780d-431e-b148-3d8383cd7c44';
  
  console.log('\n📋 Checking current entries:');
  const entriesBefore = await timeEntriesService.findByUser(userId, {
    startDate: new Date('2026-02-05'),
    endDate: new Date('2026-02-06'),
  });
  console.log(`   Total entries: ${entriesBefore.entries.length}`);
  entriesBefore.entries.forEach((e: { type: string; timestamp: Date; id: string }) => {
    console.log(`   - ${e.type}: ${e.timestamp.toISOString()} (${e.id})`);
  });
  
  console.log('\n🔍 Detecting incomplete workdays...');
  await timeEntriesService.detectAndProcessIncompleteWorkdays(userId);
  
  console.log('\n📋 Checking entries after processing:');
  const entriesAfter = await timeEntriesService.findByUser(userId, {
    startDate: new Date('2026-02-05'),
    endDate: new Date('2026-02-06'),
  });
  console.log(`   Total entries: ${entriesAfter.entries.length}`);
  entriesAfter.entries.forEach((e: { type: string; timestamp: Date; id: string }) => {
    console.log(`   - ${e.type}: ${e.timestamp.toISOString()} (${e.id})`);
  });
  
  console.log('\n📋 Checking incidents for user:');
  const incidents = await incidentsService.findAll({
    userId: userId,
  });
  console.log(`   Total incidents: ${incidents.total}`);
  incidents.incidents.forEach((inc: { type: string; autoGeneratedExitTimestamp: Date | null; id: string; incidentDate: Date }) => {
    console.log(`   - Type: ${inc.type}`);
    console.log(`     Incident Date: ${inc.incidentDate?.toISOString()}`);
    console.log(`     Auto Exit: ${inc.autoGeneratedExitTimestamp?.toISOString() || 'N/A'}`);
    console.log(`     ID: ${inc.id}`);
  });
  
  await app.close();
  console.log('\n✅ Test completed!');
  process.exit(0);
}

testAutoExit().catch(error => {
  console.error('❌ Test failed:', error);
  process.exit(1);
});
