import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';
import { TimeEntry } from '../../time-entries/entities/time-entry.entity';

export enum IncidentType {
  AUTO_EXIT_MISSING = 'auto_exit_missing',
  CONSECUTIVE_CLOCK_INS = 'consecutive_clock_ins',
  MANUAL_ADJUSTMENT = 'manual_adjustment',
  USER_CORRECTION_REQUEST = 'user_correction_request',
  OTHER = 'other',
}

export enum IncidentStatus {
  PENDING = 'pending',
  RESOLVED = 'resolved',
  DISMISSED = 'dismissed',
}

@Entity('incidents')
@Index(['userId', 'createdAt'])
@Index(['status'])
export class Incident {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id' })
  userId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column({
    type: 'enum',
    enum: IncidentType,
    default: IncidentType.OTHER,
  })
  type: IncidentType;

  @Column({
    type: 'enum',
    enum: IncidentStatus,
    default: IncidentStatus.PENDING,
  })
  status: IncidentStatus;

  @Column({ type: 'text' })
  description: string;

  @Column({ name: 'incident_date', type: 'date' })
  incidentDate: Date;

  @Column({ name: 'original_entry_timestamp', type: 'timestamp with time zone', nullable: true })
  originalEntryTimestamp: Date | null;

  @Column({ name: 'auto_generated_exit_timestamp', type: 'timestamp with time zone', nullable: true })
  autoGeneratedExitTimestamp: Date | null;

  @Column({ name: 'real_exit_timestamp', type: 'timestamp with time zone', nullable: true })
  realExitTimestamp: Date | null;

  @Column({ name: 'related_entry_id', nullable: true })
  relatedEntryId: string | null;

  @ManyToOne(() => TimeEntry, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'related_entry_id' })
  relatedEntry: TimeEntry;

  @Column({ name: 'auto_generated', default: true })
  autoGenerated: boolean;

  @Column({ name: 'resolved_by', nullable: true })
  resolvedBy: string | null;

  @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'resolved_by' })
  resolvedByUser: User;

  @Column({ name: 'resolved_at', type: 'timestamp with time zone', nullable: true })
  resolvedAt: Date | null;

  @Column({ name: 'resolution_notes', type: 'text', nullable: true })
  resolutionNotes: string | null;

  // Campos para trazabilidad de edición por admin
  @Column({ name: 'edited_by_admin', default: false })
  editedByAdmin: boolean;

  @Column({ name: 'edited_at', type: 'timestamp with time zone', nullable: true })
  editedAt: Date | null;

  @Column({ name: 'edited_by', type: 'varchar', nullable: true })
  editedBy: string | null;

  // Campos para solicitudes de corrección por usuarios
  @Column({ name: 'user_requested_time', type: 'timestamp with time zone', nullable: true })
  userRequestedTime: Date | null;

  @Column({ name: 'user_message', type: 'text', nullable: true })
  userMessage: string | null;

  @Column({ name: 'pending_admin_review', default: false })
  pendingAdminReview: boolean;

  @Column({ name: 'correction_requested_at', type: 'timestamp with time zone', nullable: true })
  correctionRequestedAt: Date | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
