'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { ExclamationTriangleIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { api } from '@/lib/api';
import Link from 'next/link';

interface Incident {
  id: string;
  userId: string;
  type: string;
  status: 'pending' | 'resolved' | 'dismissed';
  description: string;
  incidentDate: string;
  autoGeneratedExitTimestamp: string | null;
  userRequestedTime: string | null;
  userMessage: string | null;
  pendingAdminReview: boolean;
}

export function PendingIncidentsAlert() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [isVisible, setIsVisible] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  useEffect(() => {
    const fetchPendingIncidents = async () => {
      if (!session?.accessToken) {
        setIsLoading(false);
        return;
      }

      try {
        setIsLoading(true);
        setErrorMsg(null);
        
        try {
          const yesterdayResponse = await api.get<Incident[]>('/incidents/my-yesterday-pending', {
            headers: { Authorization: `Bearer ${session.accessToken}` },
          });

          if (yesterdayResponse.data.length > 0) {
            setIncidents(yesterdayResponse.data);
            setIsVisible(true);
            setIsLoading(false);
            return;
          }
        } catch (yesterdayError: any) {
          if (process.env.NODE_ENV === 'development') {
            console.warn('Error fetching yesterday incidents, trying history:', yesterdayError);
          }
        }

        const historyResponse = await api.get<Incident[]>('/incidents/my-history', {
          headers: { Authorization: `Bearer ${session.accessToken}` },
        });

        const pendingIncidents = historyResponse.data.filter(
          (incident: Incident) => 
            incident.status === 'pending' && 
            incident.type === 'auto_exit_missing'
        );

        if (pendingIncidents.length > 0) {
          setIncidents(pendingIncidents);
          setIsVisible(true);
        }
      } catch (error: any) {
        console.error('Error fetching pending incidents:', error);
        setErrorMsg(error?.response?.data?.message || error?.message || 'Error desconocido');
      } finally {
        setIsLoading(false);
      }
    };

    if (status === 'authenticated' && session?.accessToken) {
      fetchPendingIncidents();
    } else if (status === 'unauthenticated') {
      setIsLoading(false);
    }
  }, [session, status]);

  const handleDismiss = () => {
    setIsVisible(false);
    sessionStorage.setItem('incidentsAlertDismissed', 'true');
    sessionStorage.setItem('incidentsAlertLastUserId', session?.user?.id || '');
  };

  useEffect(() => {
    const dismissed = sessionStorage.getItem('incidentsAlertDismissed');
    const lastUserId = sessionStorage.getItem('incidentsAlertLastUserId');
    const currentUserId = session?.user?.id;
    
    if (currentUserId && lastUserId !== currentUserId) {
      sessionStorage.removeItem('incidentsAlertDismissed');
      sessionStorage.setItem('incidentsAlertLastUserId', currentUserId);
    } else if (dismissed === 'true') {
      setIsVisible(false);
    }
  }, [session?.user?.id]);
  
  if (isLoading) {
    return null;
  }
  
  if (!isVisible) {
    return null;
  }
  
  if (incidents.length === 0) {
    return null;
  }

  return (
    <div className="rounded-lg bg-yellow-50 border border-yellow-200 p-4 mb-6">
      <div className="flex items-start gap-4">
        <div className="flex-shrink-0">
          <ExclamationTriangleIcon className="h-6 w-6 text-yellow-600" />
        </div>
        <div className="flex-1">
          <h3 className="text-sm font-medium text-yellow-900">
            Incidencias pendientes de ayer
          </h3>
          <div className="mt-2 text-sm text-yellow-700">
            <p className="mb-2">
              Ayer olvidaste fichar tu salida. Por favor revisa la incidencia para actualizarla con tu hora real de salida.
            </p>
            <ul className="list-disc list-inside space-y-1">
              {incidents.map((incident) => (
                <li key={incident.id}>
                  Fecha: {new Date(incident.incidentDate).toLocaleDateString('es-ES')} - 
                  Salida automática a las: {incident.autoGeneratedExitTimestamp ? 
                    new Date(incident.autoGeneratedExitTimestamp).toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' }) : 
                    'No especificada'}
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-4 flex gap-3">
            <Link
              href="/dashboard/my-incidents"
              className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-yellow-700 bg-yellow-100 hover:bg-yellow-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500"
            >
              Ver incidencias y resolver
            </Link>
            <button
              onClick={handleDismiss}
              className="inline-flex items-center px-3 py-2 border border-yellow-300 text-sm leading-4 font-medium rounded-md text-yellow-700 bg-transparent hover:bg-yellow-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500"
            >
              Recordarme más tarde
            </button>
          </div>
        </div>
        <button
          onClick={handleDismiss}
          className="flex-shrink-0 -mr-1 p-1 rounded-md text-yellow-500 hover:text-yellow-700 hover:bg-yellow-100 focus:outline-none"
          aria-label="Cerrar"
        >
          <XMarkIcon className="h-5 w-5" />
        </button>
      </div>
    </div>
  );
}
