'use client';

import { useState, useEffect, useCallback } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import {
  ExclamationTriangleIcon,
  CheckCircleIcon,
  ClockIcon,
  CalendarIcon,
  XMarkIcon,
  PencilIcon,
} from '@heroicons/react/24/outline';
import { api } from '@/lib/api';
import toast from 'react-hot-toast';

interface Incident {
  id: string;
  type: 'auto_exit_missing' | 'consecutive_clock_ins' | 'manual_adjustment' | 'other';
  status: 'pending' | 'resolved' | 'dismissed';
  description: string;
  incidentDate: string;
  originalEntryTimestamp: string | null;
  autoGeneratedExitTimestamp: string | null;
  realExitTimestamp: string | null;
  userRequestedTime: string | null;
  userMessage: string | null;
  pendingAdminReview: boolean;
  createdAt: string;
}

const incidentTypeLabels: Record<string, string> = {
  auto_exit_missing: 'Salida automática por jornada incompleta',
  consecutive_clock_ins: 'Entradas consecutivas sin salida',
  manual_adjustment: 'Ajuste manual',
  other: 'Otro',
};

const statusLabels: Record<string, string> = {
  pending: 'Pendiente',
  resolved: 'Resuelta',
  dismissed: 'Descartada',
};

const statusColors: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-800',
  resolved: 'bg-green-100 text-green-800',
  dismissed: 'bg-gray-100 text-gray-800',
};

export default function UserIncidentsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Modal state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [requestedTime, setRequestedTime] = useState('');
  const [message, setMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const fetchIncidents = useCallback(async () => {
    if (!session?.accessToken) return;

    try {
      setIsLoading(true);
      setError(null);

      const response = await api.get<Incident[]>('/incidents/my-pending', {
        headers: { Authorization: `Bearer ${session.accessToken}` },
      });

      setIncidents(response.data);
    } catch (err: any) {
      console.error('Error fetching incidents:', err);
      setError(err.response?.data?.message || 'Error al cargar las incidencias');
    } finally {
      setIsLoading(false);
    }
  }, [session?.accessToken]);

  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login');
      return;
    }

    if (session?.accessToken) {
      fetchIncidents();
    }
  }, [session, status, router, fetchIncidents]);

  const openCorrectionModal = (incident: Incident) => {
    setSelectedIncident(incident);
    // Inicializar con la hora automática si existe
    if (incident.autoGeneratedExitTimestamp) {
      setRequestedTime(new Date(incident.autoGeneratedExitTimestamp).toISOString().slice(11, 16));
    } else {
      setRequestedTime('');
    }
    setMessage('');
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setSelectedIncident(null);
    setRequestedTime('');
    setMessage('');
  };

  const handleSubmitCorrection = async () => {
    if (!session?.accessToken || !selectedIncident) return;

    if (!requestedTime || !message.trim()) {
      toast.error('Por favor completa todos los campos');
      return;
    }

    try {
      setIsSubmitting(true);

      // Construir el timestamp a partir de la fecha de la incidencia y la hora proporcionada
      const incidentDate = new Date(selectedIncident.incidentDate);
      const [hours, minutes] = requestedTime.split(':');
      incidentDate.setHours(parseInt(hours), parseInt(minutes), 0, 0);

      await api.patch(
        `/incidents/${selectedIncident.id}/request-correction`,
        {
          requestedTime: incidentDate.toISOString(),
          message: message.trim(),
        },
        {
          headers: { Authorization: `Bearer ${session.accessToken}` },
        }
      );

      toast.success('Solicitud de corrección enviada correctamente');
      closeModal();
      fetchIncidents();
    } catch (err: any) {
      console.error('Error requesting correction:', err);
      toast.error(err.response?.data?.message || 'Error al enviar la solicitud');
    } finally {
      setIsSubmitting(false);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
    });
  };

  const formatTime = (dateString: string | null) => {
    if (!dateString) return 'No especificada';
    return new Date(dateString).toLocaleTimeString('es-ES', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  if (status === 'loading' || isLoading) {
    return (
      <div className="space-y-6">
        <div className="animate-pulse">
          <div className="h-8 w-48 bg-gray-200 rounded mb-4" />
          <div className="h-4 w-96 bg-gray-200 rounded mb-8" />
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-24 bg-gray-200 rounded" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-lg bg-red-50 p-4">
        <div className="flex">
          <ExclamationTriangleIcon className="h-5 w-5 text-red-400" />
          <div className="ml-3">
            <h3 className="text-sm font-medium text-red-800">Error</h3>
            <p className="mt-2 text-sm text-red-700">{error}</p>
            <button
              onClick={fetchIncidents}
              className="mt-2 text-sm font-medium text-red-600 hover:text-red-500"
            >
              Reintentar
            </button>
          </div>
        </div>
      </div>
    );
  }

  const pendingIncidents = incidents.filter((i) => i.status === 'pending');
  const resolvedIncidents = incidents.filter((i) => i.status === 'resolved');

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Mis Incidencias</h1>
        <p className="mt-1 text-sm text-gray-500">
          Gestiona las incidencias de tus fichajes
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="rounded-lg bg-yellow-50 p-4">
          <div className="flex items-center">
            <ExclamationTriangleIcon className="h-8 w-8 text-yellow-600" />
            <div className="ml-4">
              <p className="text-sm font-medium text-yellow-600">Pendientes</p>
              <p className="text-2xl font-bold text-yellow-900">{pendingIncidents.length}</p>
            </div>
          </div>
        </div>
        <div className="rounded-lg bg-green-50 p-4">
          <div className="flex items-center">
            <CheckCircleIcon className="h-8 w-8 text-green-600" />
            <div className="ml-4">
              <p className="text-sm font-medium text-green-600">Resueltas</p>
              <p className="text-2xl font-bold text-green-900">{resolvedIncidents.length}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Incidents List */}
      {incidents.length === 0 ? (
        <div className="rounded-lg border-2 border-dashed border-gray-300 p-12 text-center">
          <CheckCircleIcon className="mx-auto h-12 w-12 text-gray-400" />
          <h3 className="mt-2 text-sm font-medium text-gray-900">Sin incidencias</h3>
          <p className="mt-1 text-sm text-gray-500">
            No tienes incidencias registradas. ¡Buen trabajo!
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {incidents.map((incident) => (
            <div
              key={incident.id}
              className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"
            >
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-4">
                  <div className={`flex h-10 w-10 items-center justify-center rounded-full ${
                    incident.status === 'pending' ? 'bg-yellow-100' : 'bg-green-100'
                  }`}>
                    <ExclamationTriangleIcon className={`h-5 w-5 ${
                      incident.status === 'pending' ? 'text-yellow-600' : 'text-green-600'
                    }`} />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-medium text-gray-900">
                        {incidentTypeLabels[incident.type] || incident.type}
                      </h3>
                      <span
                        className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                          statusColors[incident.status]
                        }`}
                      >
                        {statusLabels[incident.status]}
                      </span>
                      {incident.pendingAdminReview && (
                        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-blue-100 text-blue-800">
                          En revisión
                        </span>
                      )}
                    </div>
                    <p className="mt-1 text-sm text-gray-700">{incident.description}</p>
                    <div className="mt-2 flex items-center gap-4 text-xs text-gray-500">
                      <span className="flex items-center gap-1">
                        <CalendarIcon className="h-4 w-4" />
                        {formatDate(incident.incidentDate)}
                      </span>
                      {incident.originalEntryTimestamp && (
                        <span className="flex items-center gap-1">
                          <ClockIcon className="h-4 w-4" />
                          Entrada: {formatTime(incident.originalEntryTimestamp)}
                        </span>
                      )}
                      {incident.autoGeneratedExitTimestamp && (
                        <span className="flex items-center gap-1 text-yellow-600">
                          <ClockIcon className="h-4 w-4" />
                          Salida auto: {formatTime(incident.autoGeneratedExitTimestamp)}
                        </span>
                      )}
                    </div>
                    
                    {/* Mostrar solicitud de corrección si existe */}
                    {incident.userRequestedTime && (
                      <div className="mt-3 rounded-lg bg-blue-50 p-3">
                        <p className="text-sm font-medium text-blue-900">Solicitud de corrección enviada:</p>
                        <p className="text-sm text-blue-700">
                          Hora solicitada: {formatTime(incident.userRequestedTime)}
                        </p>
                        <p className="text-sm text-blue-700 mt-1">
                          Mensaje: {incident.userMessage}
                        </p>
                      </div>
                    )}
                  </div>
                </div>

                {/* Botón de solicitar corrección */}
                {incident.status === 'pending' && 
                 incident.type === 'auto_exit_missing' && 
                 !incident.userRequestedTime && (
                  <button
                    onClick={() => openCorrectionModal(incident)}
                    className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700"
                  >
                    <PencilIcon className="h-4 w-4" />
                    Solicitar corrección
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Correction Modal */}
      {isModalOpen && selectedIncident && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900">
                Solicitar corrección
              </h2>
              <button
                onClick={closeModal}
                className="p-1 rounded-lg hover:bg-gray-100"
              >
                <XMarkIcon className="h-5 w-5 text-gray-500" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Hora real de salida
                </label>
                <input
                  type="time"
                  value={requestedTime}
                  onChange={(e) => setRequestedTime(e.target.value)}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                />
                {selectedIncident.autoGeneratedExitTimestamp && (
                  <p className="mt-1 text-xs text-gray-500">
                    Hora automática registrada: {formatTime(selectedIncident.autoGeneratedExitTimestamp)}
                  </p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Explicación
                </label>
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={3}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                  placeholder="Explica por qué necesitas corregir la hora de salida..."
                />
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <button
                onClick={closeModal}
                className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
              >
                Cancelar
              </button>
              <button
                onClick={handleSubmitCorrection}
                disabled={isSubmitting || !requestedTime || !message.trim()}
                className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isSubmitting ? 'Enviando...' : 'Enviar solicitud'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
