import { IsOptional, IsString, IsEnum, IsUUID, IsDateString, IsBooleanString } from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { IncidentStatus, IncidentType } from '../entities/incident.entity';

export class QueryIncidentsDto {
  @IsOptional()
  @IsUUID()
  userId?: string;

  @IsOptional()
  @IsEnum(IncidentType)
  type?: IncidentType;

  @IsOptional()
  @IsEnum(IncidentStatus)
  status?: IncidentStatus;

  @IsOptional()
  @IsDateString()
  startDate?: string;

  @IsOptional()
  @IsDateString()
  endDate?: string;

  @IsOptional()
  @Transform(({ value }) => value === 'true' || value === true)
  @IsBooleanString()
  pendingAdminReview?: boolean;

  @IsOptional()
  page?: number;

  @IsOptional()
  limit?: number;
}

export class ResolveIncidentDto {
  @IsOptional()
  @IsString()
  resolutionNotes?: string;

  @IsOptional()
  @IsEnum(IncidentStatus)
  status?: IncidentStatus;
}

export class CreateIncidentDto {
  @IsUUID()
  userId: string;

  @IsEnum(IncidentType)
  type: IncidentType;

  @IsString()
  description: string;

  @IsDateString()
  incidentDate: string;

  @IsOptional()
  @IsDateString()
  originalEntryTimestamp?: string;

  @IsOptional()
  @IsDateString()
  autoGeneratedExitTimestamp?: string;

  @IsOptional()
  @IsUUID()
  relatedEntryId?: string;

  @IsOptional()
  autoGenerated?: boolean;
}

export class UpdateIncidentDto {
  @IsOptional()
  @IsDateString()
  autoGeneratedExitTimestamp?: string;

  @IsOptional()
  @IsDateString()
  realExitTimestamp?: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  resolved?: boolean;

  @IsOptional()
  @IsDateString()
  resolvedAt?: string;
}

export class RequestCorrectionDto {
  @IsDateString()
  requestedTime: string;

  @IsString()
  message: string;
}
