'use client';

import { useState, useEffect, useCallback } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import {
  ExclamationTriangleIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon,
  UserIcon,
  CalendarIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  PencilIcon,
} from '@heroicons/react/24/outline';
import { api } from '@/lib/api';

interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
}

interface Incident {
  id: string;
  userId: string;
  user: User;
  type: 'auto_exit_missing' | 'consecutive_clock_ins' | 'manual_adjustment' | 'other' | 'user_correction_request';
  status: 'pending' | 'resolved' | 'dismissed';
  description: string;
  incidentDate: string;
  originalEntryTimestamp: string | null;
  autoGeneratedExitTimestamp: string | null;
  realExitTimestamp: string | null;
  autoGenerated: boolean;
  resolvedBy: string | null;
  resolvedByUser: User | null;
  resolvedAt: string | null;
  resolutionNotes: string | null;
  userRequestedTime: string | null;
  userMessage: string | null;
  pendingAdminReview: boolean;
  createdAt: string;
}

interface IncidentsResponse {
  incidents: Incident[];
  total: number;
  pendingCount: number;
  resolvedToday: number;
}

const incidentTypeLabels: Record<string, string> = {
  auto_exit_missing: 'Salida automática por jornada incompleta',
  consecutive_clock_ins: 'Entradas consecutivas sin salida',
  manual_adjustment: 'Ajuste manual',
  user_correction_request: 'Solicitud de corrección',
  other: 'Otro',
};

const statusLabels: Record<string, string> = {
  pending: 'Pendiente',
  resolved: 'Resuelta',
  dismissed: 'Descartada',
};

const statusColors: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-800',
  resolved: 'bg-green-100 text-green-800',
  dismissed: 'bg-gray-100 text-gray-800',
};

export default function IncidentsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pendingCount, setPendingCount] = useState(0);
  const [resolvedToday, setResolvedToday] = useState(0);
  const [total, setTotal] = useState(0);

  // Filters
  const [statusFilter, setStatusFilter] = useState<string>('pending');
  const [typeFilter, setTypeFilter] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState('');
  const [activeTab, setActiveTab] = useState<'incidents' | 'corrections'>('incidents');
  const [correctionRequests, setCorrectionRequests] = useState<Incident[]>([]);
  const [correctionRequestsCount, setCorrectionRequestsCount] = useState(0);

  // Modal state
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [resolutionNotes, setResolutionNotes] = useState('');
  const [isResolving, setIsResolving] = useState(false);
  
  // Edit modal state
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingIncident, setEditingIncident] = useState<Incident | null>(null);
  const [realExitTime, setRealExitTime] = useState('');
  const [incidentDescription, setIncidentDescription] = useState('');
  const [markAsResolved, setMarkAsResolved] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  const fetchIncidents = useCallback(async () => {
    if (!session?.accessToken) return;

    try {
      setIsLoading(true);
      setError(null);

      const params = new URLSearchParams();
      if (statusFilter) params.append('status', statusFilter);
      if (typeFilter) params.append('type', typeFilter);

      const response = await api.get<IncidentsResponse>(`/incidents?${params.toString()}`, {
        headers: { Authorization: `Bearer ${session.accessToken}` },
      });

      setIncidents(response.data.incidents);
      setTotal(response.data.total);
      setPendingCount(response.data.pendingCount);
      setResolvedToday(response.data.resolvedToday || 0);
    } catch (err: any) {
      console.error('Error fetching incidents:', err);
      setError(err.response?.data?.message || 'Error al cargar las incidencias');
    } finally {
      setIsLoading(false);
    }
  }, [session?.accessToken, statusFilter, typeFilter]);

  const fetchCorrectionRequests = useCallback(async () => {
    if (!session?.accessToken) return;

    try {
      const response = await api.get<{ incidents: Incident[]; total: number }>('/incidents/pending-reviews', {
        headers: { Authorization: `Bearer ${session.accessToken}` },
      });

      setCorrectionRequests(response.data.incidents);
      setCorrectionRequestsCount(response.data.total);
    } catch (err: any) {
      console.error('Error fetching correction requests:', err);
    }
  }, [session?.accessToken]);

  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/login');
      return;
    }

    if (session?.user?.role !== 'admin') {
      router.push('/dashboard');
      return;
    }

    fetchIncidents();
    fetchCorrectionRequests();
  }, [session, status, router, fetchIncidents, fetchCorrectionRequests]);

  const handleResolve = async (incidentId: string, action: 'resolved' | 'dismissed') => {
    if (!session?.accessToken) return;

    try {
      setIsResolving(true);
      await api.patch(
        `/incidents/${incidentId}/resolve`,
        {
          status: action,
          resolutionNotes: resolutionNotes || undefined,
        },
        {
          headers: { Authorization: `Bearer ${session.accessToken}` },
        }
      );

      setSelectedIncident(null);
      setResolutionNotes('');
      fetchIncidents();
    } catch (err: any) {
      console.error('Error resolving incident:', err);
      setError(err.response?.data?.message || 'Error al resolver la incidencia');
    } finally {
      setIsResolving(false);
    }
  };

  const openEditModal = (incident: Incident) => {
    setEditingIncident(incident);
    // Inicializar con la hora automática si existe, o vacía
    if (incident.realExitTimestamp) {
      setRealExitTime(new Date(incident.realExitTimestamp).toISOString().slice(11, 16));
    } else if (incident.autoGeneratedExitTimestamp) {
      setRealExitTime(new Date(incident.autoGeneratedExitTimestamp).toISOString().slice(11, 16));
    } else {
      setRealExitTime('');
    }
    setIncidentDescription(incident.description || '');
    setMarkAsResolved(false);
    setIsEditModalOpen(true);
  };

  const closeEditModal = () => {
    setIsEditModalOpen(false);
    setEditingIncident(null);
    setRealExitTime('');
    setIncidentDescription('');
    setMarkAsResolved(false);
  };

  const handleUpdateIncident = async () => {
    if (!session?.accessToken || !editingIncident) return;

    try {
      setIsEditing(true);
      
      // Construir el timestamp real a partir de la fecha de la incidencia y la hora proporcionada
      let realExitTimestamp: string | undefined;
      if (realExitTime) {
        const incidentDate = new Date(editingIncident.incidentDate);
        const [hours, minutes] = realExitTime.split(':');
        incidentDate.setHours(parseInt(hours), parseInt(minutes), 0, 0);
        realExitTimestamp = incidentDate.toISOString();
      }

      await api.patch(
        `/incidents/${editingIncident.id}`,
        {
          realExitTimestamp,
          description: incidentDescription || undefined,
          resolved: markAsResolved,
        },
        {
          headers: { Authorization: `Bearer ${session.accessToken}` },
        }
      );

      closeEditModal();
      fetchIncidents();
    } catch (err: any) {
      console.error('Error updating incident:', err);
      setError(err.response?.data?.message || 'Error al actualizar la incidencia');
    } finally {
      setIsEditing(false);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
    });
  };

  const formatTime = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('es-ES', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const filteredIncidents = incidents.filter((incident) => {
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      const userName = `${incident.user?.firstName || ''} ${incident.user?.lastName || ''}`.toLowerCase();
      const email = incident.user?.email?.toLowerCase() || '';
      return userName.includes(search) || email.includes(search);
    }
    return true;
  });

  const filteredCorrectionRequests = correctionRequests.filter((incident) => {
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      const userName = `${incident.user?.firstName || ''} ${incident.user?.lastName || ''}`.toLowerCase();
      const email = incident.user?.email?.toLowerCase() || '';
      return userName.includes(search) || email.includes(search);
    }
    return true;
  });

  const renderIncidentCard = (incident: Incident, isCorrectionRequest = false) => (
    <div
      key={incident.id}
      className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow"
    >
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-4">
          <div className={`flex h-10 w-10 items-center justify-center rounded-full ${isCorrectionRequest ? 'bg-blue-100' : 'bg-yellow-100'}`}>
            <ExclamationTriangleIcon className={`h-5 w-5 ${isCorrectionRequest ? 'text-blue-600' : 'text-yellow-600'}`} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-medium text-gray-900">
                {incident.user?.firstName} {incident.user?.lastName}
              </h3>
              <span
                className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                  statusColors[incident.status]
                }`}
              >
                {statusLabels[incident.status]}
              </span>
              {isCorrectionRequest && (
                <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-blue-100 text-blue-800">
                  Solicitud de corrección
                </span>
              )}
            </div>
            <p className="text-sm text-gray-500">{incident.user?.email}</p>
            <p className="mt-1 text-sm text-gray-700">
              {incidentTypeLabels[incident.type] || incident.type}
            </p>
            
            {/* Mostrar información de la solicitud de corrección */}
            {incident.userRequestedTime && (
              <div className="mt-2 rounded-lg bg-blue-50 p-3">
                <p className="text-sm font-medium text-blue-900">Solicitud del usuario:</p>
                <p className="text-sm text-blue-700">
                  Hora solicitada: {formatTime(incident.userRequestedTime)}
                </p>
                <p className="text-sm text-blue-700 mt-1">
                  Mensaje: {incident.userMessage}
                </p>
              </div>
            )}
            
            <div className="mt-2 flex items-center gap-4 text-xs text-gray-500">
              <span className="flex items-center gap-1">
                <CalendarIcon className="h-4 w-4" />
                {formatDate(incident.incidentDate)}
              </span>
              {incident.originalEntryTimestamp && (
                <span className="flex items-center gap-1">
                  <ClockIcon className="h-4 w-4" />
                  Entrada: {formatTime(incident.originalEntryTimestamp)}
                </span>
              )}
              {incident.autoGeneratedExitTimestamp && (
                <span className="flex items-center gap-1 text-yellow-600">
                  <ClockIcon className="h-4 w-4" />
                  Salida auto: {formatTime(incident.autoGeneratedExitTimestamp)}
                </span>
              )}
            </div>
          </div>
        </div>

        {incident.status === 'pending' && (
          <div className="flex gap-2">
            {incident.type === 'auto_exit_missing' && (
              <button
                onClick={() => openEditModal(incident)}
                className="rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700"
              >
                Editar
              </button>
            )}
            <button
              onClick={() => setSelectedIncident(incident)}
              className="rounded-lg bg-primary-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-primary-700"
            >
              Resolver
            </button>
            <button
              onClick={() => handleResolve(incident.id, 'dismissed')}
              className="rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
              Descartar
            </button>
          </div>
        )}

        {incident.status !== 'pending' && incident.resolvedByUser && (
          <div className="text-right text-xs text-gray-500">
            <p>
              Resuelta por: {incident.resolvedByUser.firstName}{' '}
              {incident.resolvedByUser.lastName}
            </p>
            {incident.resolvedAt && <p>{formatDate(incident.resolvedAt)}</p>}
            {incident.resolutionNotes && (
              <p className="mt-1 text-gray-600">{incident.resolutionNotes}</p>
            )}
          </div>
        )}
      </div>
    </div>
  );

  if (status === 'loading' || isLoading) {
    return (
      <div className="space-y-6">
        <div className="animate-pulse">
          <div className="h-8 w-48 bg-gray-200 rounded mb-4" />
          <div className="h-4 w-96 bg-gray-200 rounded mb-8" />
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-24 bg-gray-200 rounded" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-lg bg-red-50 p-4">
        <div className="flex">
          <XCircleIcon className="h-5 w-5 text-red-400" />
          <div className="ml-3">
            <h3 className="text-sm font-medium text-red-800">Error</h3>
            <p className="mt-2 text-sm text-red-700">{error}</p>
            <button
              onClick={fetchIncidents}
              className="mt-2 text-sm font-medium text-red-600 hover:text-red-500"
            >
              Reintentar
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Incidencias</h1>
        <p className="mt-1 text-sm text-gray-500">
          Gestiona las incidencias de fichaje detectadas automáticamente
        </p>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200">
        <nav className="-mb-px flex space-x-8">
          <button
            onClick={() => setActiveTab('incidents')}
            className={`py-4 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'incidents'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            Incidencias
            <span className="ml-2 rounded-full bg-yellow-100 px-2.5 py-0.5 text-xs font-medium text-yellow-800">
              {pendingCount}
            </span>
          </button>
          <button
            onClick={() => setActiveTab('corrections')}
            className={`py-4 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'corrections'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            Solicitudes de corrección
            <span className="ml-2 rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800">
              {correctionRequestsCount}
            </span>
          </button>
        </nav>
      </div>

      {activeTab === 'incidents' && (
        <>
          {/* Stats */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded-lg bg-yellow-50 p-4">
              <div className="flex items-center">
                <ExclamationTriangleIcon className="h-8 w-8 text-yellow-600" />
                <div className="ml-4">
                  <p className="text-sm font-medium text-yellow-600">Pendientes</p>
                  <p className="text-2xl font-bold text-yellow-900">{pendingCount}</p>
                </div>
              </div>
            </div>
            <div className="rounded-lg bg-purple-50 p-4">
              <div className="flex items-center">
                <PencilIcon className="h-8 w-8 text-purple-600" />
                <div className="ml-4">
                  <p className="text-sm font-medium text-purple-600">Solicitudes</p>
                  <p className="text-2xl font-bold text-purple-900">{correctionRequestsCount}</p>
                </div>
              </div>
            </div>
            <div className="rounded-lg bg-green-50 p-4">
              <div className="flex items-center">
                <CheckCircleIcon className="h-8 w-8 text-green-600" />
                <div className="ml-4">
                  <p className="text-sm font-medium text-green-600">Resueltas hoy</p>
                  <p className="text-2xl font-bold text-green-900">{resolvedToday}</p>
                </div>
              </div>
            </div>
            <div className="rounded-lg bg-blue-50 p-4">
              <div className="flex items-center">
                <CalendarIcon className="h-8 w-8 text-blue-600" />
                <div className="ml-4">
                  <p className="text-sm font-medium text-blue-600">Total este mes</p>
                  <p className="text-2xl font-bold text-blue-900">{total}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Filters */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-1 gap-4">
              <div className="relative flex-1 max-w-xs">
                <MagnifyingGlassIcon className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  placeholder="Buscar por usuario..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full rounded-lg border border-gray-300 py-2 pl-10 pr-4 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                />
              </div>

              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="rounded-lg border border-gray-300 py-2 pl-3 pr-8 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
              >
                <option value="">Todos los estados</option>
                <option value="pending">Pendientes</option>
                <option value="resolved">Resueltas</option>
                <option value="dismissed">Descartadas</option>
              </select>

              <select
                value={typeFilter}
                onChange={(e) => setTypeFilter(e.target.value)}
                className="rounded-lg border border-gray-300 py-2 pl-3 pr-8 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
              >
                <option value="">Todos los tipos</option>
                <option value="auto_exit_missing">Salida automática</option>
                <option value="consecutive_clock_ins">Entradas consecutivas</option>
                <option value="manual_adjustment">Ajuste manual</option>
              </select>
            </div>
          </div>

          {/* Incidents List */}
          {filteredIncidents.length === 0 ? (
            <div className="rounded-lg border-2 border-dashed border-gray-300 p-12 text-center">
              <ExclamationTriangleIcon className="mx-auto h-12 w-12 text-gray-400" />
              <h3 className="mt-2 text-sm font-medium text-gray-900">No hay incidencias</h3>
              <p className="mt-1 text-sm text-gray-500">
                {statusFilter === 'pending'
                  ? 'No hay incidencias pendientes por resolver'
                  : 'No se encontraron incidencias con los filtros seleccionados'}
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredIncidents.map((incident) => renderIncidentCard(incident, false))}
            </div>
          )}
        </>
      )}

      {activeTab === 'corrections' && (
        <>
          {/* Stats for corrections */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <div className="rounded-lg bg-blue-50 p-4">
              <div className="flex items-center">
                <ExclamationTriangleIcon className="h-8 w-8 text-blue-600" />
                <div className="ml-4">
                  <p className="text-sm font-medium text-blue-600">Solicitudes pendientes</p>
                  <p className="text-2xl font-bold text-blue-900">{correctionRequestsCount}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Search for corrections */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="relative flex-1 max-w-xs">
              <MagnifyingGlassIcon className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
              <input
                type="text"
                placeholder="Buscar por usuario..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full rounded-lg border border-gray-300 py-2 pl-10 pr-4 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
              />
            </div>
          </div>

          {/* Correction Requests List */}
          {filteredCorrectionRequests.length === 0 ? (
            <div className="rounded-lg border-2 border-dashed border-gray-300 p-12 text-center">
              <CheckCircleIcon className="mx-auto h-12 w-12 text-gray-400" />
              <h3 className="mt-2 text-sm font-medium text-gray-900">No hay solicitudes</h3>
              <p className="mt-1 text-sm text-gray-500">
                No hay solicitudes de corrección pendientes de revisión
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredCorrectionRequests.map((incident) => renderIncidentCard(incident, true))}
            </div>
          )}
        </>
      )}

      {/* Resolution Modal */}
      {selectedIncident && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl">
            <h2 className="text-lg font-semibold text-gray-900">Resolver incidencia</h2>
            <p className="mt-1 text-sm text-gray-500">
              Usuario: {selectedIncident.user?.firstName} {selectedIncident.user?.lastName}
            </p>
            <p className="text-sm text-gray-500">
              Fecha: {formatDate(selectedIncident.incidentDate)}
            </p>

            <div className="mt-4">
              <label className="block text-sm font-medium text-gray-700">
                Notas de resolución (opcional)
              </label>
              <textarea
                value={resolutionNotes}
                onChange={(e) => setResolutionNotes(e.target.value)}
                rows={3}
                className="mt-1 w-full rounded-lg border border-gray-300 p-2 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                placeholder="Añade notas sobre la resolución..."
              />
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <button
                onClick={() => {
                  setSelectedIncident(null);
                  setResolutionNotes('');
                }}
                className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
              >
                Cancelar
              </button>
              <button
                onClick={() => handleResolve(selectedIncident.id, 'resolved')}
                disabled={isResolving}
                className="rounded-lg bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700 disabled:opacity-50"
              >
                {isResolving ? 'Resolviendo...' : 'Marcar como resuelta'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Incident Modal */}
      {isEditModalOpen && editingIncident && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl">
            <h2 className="text-lg font-semibold text-gray-900">Editar incidencia</h2>
            <p className="mt-1 text-sm text-gray-500">
              Fecha: {formatDate(editingIncident.incidentDate)}
            </p>

            <div className="mt-4 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Hora real de salida
                </label>
                <input
                  type="time"
                  value={realExitTime}
                  onChange={(e) => setRealExitTime(e.target.value)}
                  className="mt-1 w-full rounded-lg border border-gray-300 p-2 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                />
                {editingIncident.autoGeneratedExitTimestamp && (
                  <p className="mt-1 text-xs text-gray-500">
                    Hora automática: {formatTime(editingIncident.autoGeneratedExitTimestamp)}
                  </p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Explicación de qué ocurrió
                </label>
                <textarea
                  value={incidentDescription}
                  onChange={(e) => setIncidentDescription(e.target.value)}
                  rows={3}
                  className="mt-1 w-full rounded-lg border border-gray-300 p-2 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                  placeholder="Explica qué ocurrió (ej: Tuve una reunión que se alargó, salí más tarde...)"
                />
              </div>

              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="markResolved"
                  checked={markAsResolved}
                  onChange={(e) => setMarkAsResolved(e.target.checked)}
                  className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                />
                <label htmlFor="markResolved" className="text-sm font-medium text-gray-700">
                  Marcar como resuelta
                </label>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <button
                onClick={closeEditModal}
                className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
              >
                Cancelar
              </button>
              <button
                onClick={handleUpdateIncident}
                disabled={isEditing}
                className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
              >
                {isEditing ? 'Guardando...' : 'Guardar cambios'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
